const types = {
    SEARCH_MOVIES: "SEARCH_MOVIES",
    DISPLAY_MOVIES: "DISPLAY_MOVIES",
    ADD_FAVORITES: "ADD_FAVORITES",
    MOVIE_DETAILS: "MOVIE_DETAILS",
    CHANGE_SEARCHTERM: "CHANGE_SEARCHTERM"
}

export default types
